name: Sync Docs to Notion

on:
  push:
    branches:
      - main
    paths:
      - "**.md"

jobs:
  notion-sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Sync markdown to Notion
        uses: pechorin/sync-repo-docs-to-notion@main
        env:
          NOTION_TOKEN: ${{ secrets.SKOGAI_NOTION_API_KEY }}
          NOTION_ROOT_PAGE_ID: 378d9ad9db9d803ca8ecea2e3dc60b2c
          FOLDER: ${{ github.workspace }}
          RELATIVE_URLS_ROOT: ${{ github.server_url }}/${{ github.repository }}
          IGNORE_CREATE_ERRORS: 1
