name: Copilot Workflow Assistant

# This is the caller workflow that repos add to their .github/workflows/
# It invokes the org-level reusable workflow

on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]
  issues:
    types: [opened, assigned]
  pull_request_review:
    types: [submitted]

jobs:
  call-copilot:
    # Only trigger when @copilot is mentioned
    if: |
      (github.event_name == 'issue_comment' && contains(github.event.comment.body, '@copilot')) ||
      (github.event_name == 'pull_request_review_comment' && contains(github.event.comment.body, '@copilot')) ||
      (github.event_name == 'pull_request_review' && contains(github.event.review.body, '@copilot')) ||
      (github.event_name == 'issues' && (contains(github.event.issue.body, '@copilot') || contains(github.event.issue.title, '@copilot')))

    uses: SkogAI/.github/.github/workflows/copilot-workflow-manager.yml@master
    secrets:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
